server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/myBlog?characterEncoding=utf-8
    username: root
    password: 789456
commonConfig:
  commonUploadFilePath: https://zouchenwd.cn/
  uploadPath: /Users/zouchen/work/javaProject/myBlog/src/main/resources/static/
logging:
  config: classpath:log4j2-prod.xml
